In [3]:
import numpy as np
from sklearn import linear_model

In [40]:
k = 20
n = 4
m = 2

x = np.random.randn(k+1, n)
u = np.random.randn(k, m)

Y = x[1:,:]
X = np.ones((k, n+m))
X[:,:n] = x[:-1,:].copy()
X[:,n:] = u.copy()

regr = linear_model.LinearRegression()

regr.fit(X, Y)

print(regr.coef_)
print(regr.intercept_)
print(regr.score(X, Y))

[[-0.12852077  0.03866078 -0.02912133  0.15634651 -0.26251675 -0.30200239]
 [-0.58146538  0.33798035  0.11170195 -0.42144139 -0.3034823  -0.27778773]
 [-0.30361632  0.18929392 -0.40961882 -0.46523293  0.23720344  0.15813627]
 [ 0.01453444  0.20055802 -0.1631015   0.23791994  0.24131038  0.17121039]]
[  2.05868265e-04   1.47407301e-01   2.44105906e-01  -4.58799902e-02]
0.333920111693


In [41]:
print(regr.predict(X))
print(Y)

[[ 0.17433427 -0.81006359 -0.30296388  0.2324035 ]
 [ 0.05787517 -0.56387975  0.5741191   0.18599073]
 [-0.58391373 -0.36774076  0.46434188  0.27202242]
 [-0.00774013  0.80739107  0.44541993 -0.59497548]
 [-0.03326883  0.57781003  0.36569527 -0.28595267]
 [-0.54071907  0.62785969  0.70541906  0.06349263]
 [ 0.47331683  0.10398676 -0.17938971  0.90670104]
 [-0.43881099 -0.71368343  0.3052561   0.64914572]
 [ 0.4514487  -0.00425581 -0.54985679 -0.17563603]
 [-0.34307411  0.07370723  0.66173106  0.16025656]
 [ 0.6768679  -0.44039443 -1.20457273 -0.62211157]
 [ 0.0335959  -0.64758062 -0.0750411   0.16493418]
 [-0.69042285 -0.43047316 -0.01640353 -0.37059615]
 [-0.03975126  0.9676999   0.65410952 -0.27077695]
 [-1.06001005  0.33288685  2.00901901  0.43205438]
 [ 0.54320985  1.62722413 -0.73658981 -0.40452905]
 [ 0.05678534  0.69669371  0.78279466  0.1901613 ]
 [-0.10780187 -0.3884373  -0.35671853  0.01500231]
 [ 0.24986302 -0.2167269   1.38238505  0.18185264]
 [-0.3553291  -0.3781726  -0.18