In [1]:
import numpy as np
from drl.utilities import finite_difference

x = np.random.randn(2, 4)
u = np.random.randn(2, 2)

fun = lambda xu: xu[:,:2]*xu[:,4:]

In [2]:
finite_difference(fun, np.hstack((x,u)))




[[-0.26775729  1.68457577  0.19311283  1.85309876 -0.14044003 -1.51844975]
 [-0.05208999  0.20063422  0.22146761  1.73297026 -0.46372612  1.33842052]]
K, n:  (2, 6)
H:  (12, 6)
X:  (2, 12, 6)
Y:  (2, 12, 2)


array([[[-0.14044003,  0.        ],
        [ 0.        , -1.51844975],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ],
        [-0.26775729,  0.        ],
        [ 0.        ,  1.68457577]],

       [[-0.46372612,  0.        ],
        [ 0.        ,  1.33842052],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ],
        [-0.05208999,  0.        ],
        [ 0.        ,  0.20063422]]])