In [45]:
import numpy as np

def fun(x):
    return np.sum(x**2, axis=1)

x = np.random.randn(5, 2)
h = 1

In [46]:
K, n = x.shape
H = np.vstack((-h*np.eye(n), h*np.eye(n)))
X = x[:, None, :] + H[None, :, :]
Y = []
for i in range(K):
    Y.append(fun(X[i]))
Y = np.array(Y)
D = (Y[:, n:] - Y[:, 0:n])
J = D/h/2

In [47]:
print(X)
print("")
print(fun(X[0]))
print("")
print(Y)
print("")
print(Y[0, 1:])
print(Y[0, 0:1])
print(D)
print(J)

[[[-1.48952144  0.01208299]
  [-0.48952144 -0.98791701]
  [ 0.51047856  0.01208299]
  [-0.48952144  1.01208299]]

 [[-2.09118805 -0.33622546]
  [-1.09118805 -1.33622546]
  [-0.09118805 -0.33622546]
  [-1.09118805  0.66377454]]

 [[-0.32143729  1.15279005]
  [ 0.67856271  0.15279005]
  [ 1.67856271  1.15279005]
  [ 0.67856271  2.15279005]]

 [[ 0.5623391   1.80288194]
  [ 1.5623391   0.80288194]
  [ 2.5623391   1.80288194]
  [ 1.5623391   2.80288194]]

 [[-1.17462107 -1.49753911]
  [-0.17462107 -2.49753911]
  [ 0.82537893 -1.49753911]
  [-0.17462107 -0.49753911]]]

[ 2.21882011  1.21561126  0.26073436  1.26394322]

[[  2.21882011   1.21561126   0.26073436   1.26394322]
 [  4.48611504   2.97618984   0.12136282   1.63128801]
 [  1.43224684   0.48379216   4.14649769   5.09495237]
 [  3.56660857   3.08552289   9.81596499  10.29705067]
 [  3.62235805   6.26819413   2.92387376   0.27803769]]

[ 1.21561126  0.26073436  1.26394322]
[ 2.21882011]
[[-1.95808575  0.04833196]
 [-4.36475222 -1.34490

In [30]:
np.sum(X[0]**2, axis=1)

array([ 9.05547696,  9.05547505,  9.05548885])